### ISSUE TITLE
No authentication mechanism

### ISSUE THREAD

**Issue by sbuljat** [tivankov/FastApi_HungryFork#5]
https://github.com/tivankov/FastApi_HungryFork/blob/6c26d87b8833f97129f321dd5403f6147588b357/app.py#L29

There is no user authentication and authorisation process defined within the application: signup, login, edit, ...
This is needed to protect other routes like creating, updating and deleting menus by user.

-5 points

**Comment by tivankov** [comment]
Fixed issue
